package pavishka.coloring.book.Activities.Screens;

import android.graphics.Bitmap;

import java.util.ArrayList;

import pavishka.coloring.book.R;


public class ScreenConstable {
    public static final String DIR_GRAPH = "graph";
    public static final String JSON_ARRAY_NAME = "Grid";
    public static final String JSON_COLOR = "Color";
    public static final String JSON_COLUMN = "column";
    public static final String JSON_ROW = "row";
    public static final String PICTURE_CODE = "grid_picture";
    public static boolean MUSIC_SETTING = false;
    public static int SELECTED_TOOL = 0;
    public static boolean SOUND_SETTING = false;
    public static boolean erase = false;
    public static float eraseX = 0.0f;
    public static float eraseY = 0.0f;
    public static boolean eraser = false;
    public static int[] expPixels = null;
    public static int heightInPixels = 0;
    public static boolean hint_pixelart = true;
    public static int ppHeight = 0;
    public static int ppWidth = 0;
    public static int ratioX = 0;
    public static int ratioY = 0;
    public static double screenRatio = 0.0d;
    public static Bitmap selectedPatternBitmap = null;
    public static int selectedTool = 0;
    public static Integer[] selected_bitmapIds = null;
    public static int selected_color = 0;
    public static int strokeWidth = 0;
    public static boolean updateChecked = false;
    public static int widthInPixels;
    public static boolean isBackFromGlow = false;
    public static int TYPE_FILL = 0;
    public static int drawHeight = 700;
    public static int drawWidth = 700;
    public static int onSizeCalled = 0;
    public static int brushSize = 20;
    public static int DRAW_COLOR = 0;
    public static int eraseWidth = 50;
    public static boolean isBackFromDrawActivity = false;
    public static boolean showNewApp = false;
    public static boolean fromGridActivityColoringBook = false;
    public static Bitmap selectedImageFromBitmap = null;
    public static int[] pixels = null;
    public static float eraseR = 30.0f;
    public static int ERASER_WIDTH = 50;
    public static int[] colorArray = {R.color.black1, R.color.color13, R.color.brown1, R.color.color10, R.color.orange1, R.color.pink1, R.color.purple1, R.color.red1, R.color.white1, R.color.yellow1, R.color.skin, R.color.grey};
    static Integer[] aNull = null;
    static ArrayList<Integer> U = null;
    public static int anInt5 = 0;
    static int anInt8 = 0;
    static boolean aBoolean1 = true;
    static int anInt14 = 5;
    static Integer[] fifa = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.fefacup_1), Integer.valueOf((int) R.drawable.fefacup_2), Integer.valueOf((int) R.drawable.fefacup_3), Integer.valueOf((int) R.drawable.fefacup_4), Integer.valueOf((int) R.drawable.fefacup_5), Integer.valueOf((int) R.drawable.fefacup_6)};
    static Integer[] superhiro = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.fefa_1), Integer.valueOf((int) R.drawable.fefa_2), Integer.valueOf((int) R.drawable.fefa_3), Integer.valueOf((int) R.drawable.fefa_4), Integer.valueOf((int) R.drawable.fefa_5), Integer.valueOf((int) R.drawable.fefa_6), Integer.valueOf((int) R.drawable.fefa_7), Integer.valueOf((int) R.drawable.fefa_8), Integer.valueOf((int) R.drawable.fefa_9), Integer.valueOf((int) R.drawable.fefa_10), Integer.valueOf((int) R.drawable.fefa_11), Integer.valueOf((int) R.drawable.fefa_12), Integer.valueOf((int) R.drawable.fefa_13), Integer.valueOf((int) R.drawable.fefa_14), Integer.valueOf((int) R.drawable.fefa_15), Integer.valueOf((int) R.drawable.fefa_16), Integer.valueOf((int) R.drawable.fefa_17), Integer.valueOf((int) R.drawable.fefa_18), Integer.valueOf((int) R.drawable.fefa_19), Integer.valueOf((int) R.drawable.fefa_20), Integer.valueOf((int) R.drawable.fefa_21), Integer.valueOf((int) R.drawable.fefa_22), Integer.valueOf((int) R.drawable.fefa_23), Integer.valueOf((int) R.drawable.fefa_24), Integer.valueOf((int) R.drawable.fefa_25), Integer.valueOf((int) R.drawable.fefa_26), Integer.valueOf((int) R.drawable.fefa_27), Integer.valueOf((int) R.drawable.fefa_28), Integer.valueOf((int) R.drawable.fefa_29)};
    static Integer[] integers5 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.a1), Integer.valueOf((int) R.drawable.a2), Integer.valueOf((int) R.drawable.a3), Integer.valueOf((int) R.drawable.a4), Integer.valueOf((int) R.drawable.a5), Integer.valueOf((int) R.drawable.a6), Integer.valueOf((int) R.drawable.a7), Integer.valueOf((int) R.drawable.a8), Integer.valueOf((int) R.drawable.a9), Integer.valueOf((int) R.drawable.a10), Integer.valueOf((int) R.drawable.a11), Integer.valueOf((int) R.drawable.a12), Integer.valueOf((int) R.drawable.a13), Integer.valueOf((int) R.drawable.a14), Integer.valueOf((int) R.drawable.a15), Integer.valueOf((int) R.drawable.a16), Integer.valueOf((int) R.drawable.a17), Integer.valueOf((int) R.drawable.a18), Integer.valueOf((int) R.drawable.a19), Integer.valueOf((int) R.drawable.a20), Integer.valueOf((int) R.drawable.a21), Integer.valueOf((int) R.drawable.a22), Integer.valueOf((int) R.drawable.a23), Integer.valueOf((int) R.drawable.a24), Integer.valueOf((int) R.drawable.a25), Integer.valueOf((int) R.drawable.a26), Integer.valueOf((int) R.drawable.a27), Integer.valueOf((int) R.drawable.a28), Integer.valueOf((int) R.drawable.a29), Integer.valueOf((int) R.drawable.a30), Integer.valueOf((int) R.drawable.a31), Integer.valueOf((int) R.drawable.a32), Integer.valueOf((int) R.drawable.a33), Integer.valueOf((int) R.drawable.a34), Integer.valueOf((int) R.drawable.a35), Integer.valueOf((int) R.drawable.a36), Integer.valueOf((int) R.drawable.a37), Integer.valueOf((int) R.drawable.a38)};
    static Integer[] integers6 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.t1), Integer.valueOf((int) R.drawable.t2), Integer.valueOf((int) R.drawable.t3), Integer.valueOf((int) R.drawable.t4), Integer.valueOf((int) R.drawable.t5), Integer.valueOf((int) R.drawable.t6), Integer.valueOf((int) R.drawable.t7), Integer.valueOf((int) R.drawable.t8), Integer.valueOf((int) R.drawable.t9), Integer.valueOf((int) R.drawable.t10), Integer.valueOf((int) R.drawable.t11), Integer.valueOf((int) R.drawable.t12), Integer.valueOf((int) R.drawable.t13), Integer.valueOf((int) R.drawable.t14), Integer.valueOf((int) R.drawable.t15), Integer.valueOf((int) R.drawable.t16), Integer.valueOf((int) R.drawable.t17), Integer.valueOf((int) R.drawable.t18), Integer.valueOf((int) R.drawable.t19), Integer.valueOf((int) R.drawable.t20), Integer.valueOf((int) R.drawable.t21), Integer.valueOf((int) R.drawable.t22), Integer.valueOf((int) R.drawable.t23), Integer.valueOf((int) R.drawable.t24), Integer.valueOf((int) R.drawable.t25), Integer.valueOf((int) R.drawable.t26)};
    static Integer[] integers7 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.s1), Integer.valueOf((int) R.drawable.s2), Integer.valueOf((int) R.drawable.s3), Integer.valueOf((int) R.drawable.s4), Integer.valueOf((int) R.drawable.s5), Integer.valueOf((int) R.drawable.s6), Integer.valueOf((int) R.drawable.s7), Integer.valueOf((int) R.drawable.s8), Integer.valueOf((int) R.drawable.s9), Integer.valueOf((int) R.drawable.s10), Integer.valueOf((int) R.drawable.s11), Integer.valueOf((int) R.drawable.s12), Integer.valueOf((int) R.drawable.s13), Integer.valueOf((int) R.drawable.s14), Integer.valueOf((int) R.drawable.s15), Integer.valueOf((int) R.drawable.s16), Integer.valueOf((int) R.drawable.s17), Integer.valueOf((int) R.drawable.s18), Integer.valueOf((int) R.drawable.s19), Integer.valueOf((int) R.drawable.s20), Integer.valueOf((int) R.drawable.s21), Integer.valueOf((int) R.drawable.s22), Integer.valueOf((int) R.drawable.s23), Integer.valueOf((int) R.drawable.s24), Integer.valueOf((int) R.drawable.s25)};
    static Integer[] integers8 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.fr1), Integer.valueOf((int) R.drawable.fr2), Integer.valueOf((int) R.drawable.fr3), Integer.valueOf((int) R.drawable.fr4), Integer.valueOf((int) R.drawable.fr5), Integer.valueOf((int) R.drawable.fr6), Integer.valueOf((int) R.drawable.fr7), Integer.valueOf((int) R.drawable.fr8), Integer.valueOf((int) R.drawable.fr9), Integer.valueOf((int) R.drawable.fr10), Integer.valueOf((int) R.drawable.fr11), Integer.valueOf((int) R.drawable.fr12), Integer.valueOf((int) R.drawable.fr13), Integer.valueOf((int) R.drawable.fr14), Integer.valueOf((int) R.drawable.fr15), Integer.valueOf((int) R.drawable.fr16), Integer.valueOf((int) R.drawable.fr17), Integer.valueOf((int) R.drawable.fr18), Integer.valueOf((int) R.drawable.fr19), Integer.valueOf((int) R.drawable.fr20), Integer.valueOf((int) R.drawable.fr21), Integer.valueOf((int) R.drawable.fr22), Integer.valueOf((int) R.drawable.fr23), Integer.valueOf((int) R.drawable.fr24), Integer.valueOf((int) R.drawable.fr25)};
    static Integer[] integers9 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.f1), Integer.valueOf((int) R.drawable.f2), Integer.valueOf((int) R.drawable.f3), Integer.valueOf((int) R.drawable.f4), Integer.valueOf((int) R.drawable.f5), Integer.valueOf((int) R.drawable.f6), Integer.valueOf((int) R.drawable.f7), Integer.valueOf((int) R.drawable.f8), Integer.valueOf((int) R.drawable.f9), Integer.valueOf((int) R.drawable.f10), Integer.valueOf((int) R.drawable.f11), Integer.valueOf((int) R.drawable.f12), Integer.valueOf((int) R.drawable.f13), Integer.valueOf((int) R.drawable.f14), Integer.valueOf((int) R.drawable.f15), Integer.valueOf((int) R.drawable.f16), Integer.valueOf((int) R.drawable.f17), Integer.valueOf((int) R.drawable.f18), Integer.valueOf((int) R.drawable.f19), Integer.valueOf((int) R.drawable.f20), Integer.valueOf((int) R.drawable.f21), Integer.valueOf((int) R.drawable.f22), Integer.valueOf((int) R.drawable.f23), Integer.valueOf((int) R.drawable.f24), Integer.valueOf((int) R.drawable.f25), Integer.valueOf((int) R.drawable.f26), Integer.valueOf((int) R.drawable.f27), Integer.valueOf((int) R.drawable.f28), Integer.valueOf((int) R.drawable.f29), Integer.valueOf((int) R.drawable.f30), Integer.valueOf((int) R.drawable.f31), Integer.valueOf((int) R.drawable.f32), Integer.valueOf((int) R.drawable.f33), Integer.valueOf((int) R.drawable.f34), Integer.valueOf((int) R.drawable.f35), Integer.valueOf((int) R.drawable.f36), Integer.valueOf((int) R.drawable.f37), Integer.valueOf((int) R.drawable.f38)};
    static Integer[] integers10 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.v1), Integer.valueOf((int) R.drawable.v19), Integer.valueOf((int) R.drawable.v3), Integer.valueOf((int) R.drawable.v4), Integer.valueOf((int) R.drawable.v5), Integer.valueOf((int) R.drawable.v6), Integer.valueOf((int) R.drawable.v7), Integer.valueOf((int) R.drawable.v8), Integer.valueOf((int) R.drawable.v9), Integer.valueOf((int) R.drawable.v10), Integer.valueOf((int) R.drawable.v11), Integer.valueOf((int) R.drawable.v12), Integer.valueOf((int) R.drawable.v13), Integer.valueOf((int) R.drawable.v15), Integer.valueOf((int) R.drawable.v16), Integer.valueOf((int) R.drawable.v17), Integer.valueOf((int) R.drawable.v14), Integer.valueOf((int) R.drawable.v18), Integer.valueOf((int) R.drawable.v20), Integer.valueOf((int) R.drawable.v21), Integer.valueOf((int) R.drawable.v22), Integer.valueOf((int) R.drawable.v2)};
    static Integer[] integers11 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.alph_a), Integer.valueOf((int) R.drawable.alph_b), Integer.valueOf((int) R.drawable.alph_c), Integer.valueOf((int) R.drawable.alph_d), Integer.valueOf((int) R.drawable.alph_e), Integer.valueOf((int) R.drawable.alph_f), Integer.valueOf((int) R.drawable.alph_g), Integer.valueOf((int) R.drawable.alph_h), Integer.valueOf((int) R.drawable.alph_i), Integer.valueOf((int) R.drawable.alph_j), Integer.valueOf((int) R.drawable.alph_k), Integer.valueOf((int) R.drawable.alph_l), Integer.valueOf((int) R.drawable.alph_m), Integer.valueOf((int) R.drawable.alph_n), Integer.valueOf((int) R.drawable.alph_o), Integer.valueOf((int) R.drawable.alph_p), Integer.valueOf((int) R.drawable.alph_q), Integer.valueOf((int) R.drawable.alph_r), Integer.valueOf((int) R.drawable.alph_s), Integer.valueOf((int) R.drawable.alph_t), Integer.valueOf((int) R.drawable.alph_u), Integer.valueOf((int) R.drawable.alph_v), Integer.valueOf((int) R.drawable.alph_w), Integer.valueOf((int) R.drawable.alph_x), Integer.valueOf((int) R.drawable.alph_y), Integer.valueOf((int) R.drawable.alph_z)};
    static Integer[] integers12 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.n1), Integer.valueOf((int) R.drawable.n2), Integer.valueOf((int) R.drawable.n3), Integer.valueOf((int) R.drawable.n4), Integer.valueOf((int) R.drawable.n5), Integer.valueOf((int) R.drawable.n6), Integer.valueOf((int) R.drawable.n7), Integer.valueOf((int) R.drawable.n8), Integer.valueOf((int) R.drawable.n9), Integer.valueOf((int) R.drawable.n10), Integer.valueOf((int) R.drawable.n11), Integer.valueOf((int) R.drawable.n12), Integer.valueOf((int) R.drawable.n13), Integer.valueOf((int) R.drawable.n14), Integer.valueOf((int) R.drawable.n15), Integer.valueOf((int) R.drawable.n16), Integer.valueOf((int) R.drawable.n17), Integer.valueOf((int) R.drawable.n18), Integer.valueOf((int) R.drawable.n19), Integer.valueOf((int) R.drawable.n20)};
    static Integer[] integers13 = {Integer.valueOf((int) R.drawable.black), Integer.valueOf((int) R.drawable.g1), Integer.valueOf((int) R.drawable.g2), Integer.valueOf((int) R.drawable.g3), Integer.valueOf((int) R.drawable.g4), Integer.valueOf((int) R.drawable.g5), Integer.valueOf((int) R.drawable.g6), Integer.valueOf((int) R.drawable.g7), Integer.valueOf((int) R.drawable.g8), Integer.valueOf((int) R.drawable.g9), Integer.valueOf((int) R.drawable.g10), Integer.valueOf((int) R.drawable.g11), Integer.valueOf((int) R.drawable.g12), Integer.valueOf((int) R.drawable.g13), Integer.valueOf((int) R.drawable.g14), Integer.valueOf((int) R.drawable.g15), Integer.valueOf((int) R.drawable.g16), Integer.valueOf((int) R.drawable.g17), Integer.valueOf((int) R.drawable.g18), Integer.valueOf((int) R.drawable.g19), Integer.valueOf((int) R.drawable.g20), Integer.valueOf((int) R.drawable.g21), Integer.valueOf((int) R.drawable.g22), Integer.valueOf((int) R.drawable.g23), Integer.valueOf((int) R.drawable.g24), Integer.valueOf((int) R.drawable.g25), Integer.valueOf((int) R.drawable.g26), Integer.valueOf((int) R.drawable.g27), Integer.valueOf((int) R.drawable.g28), Integer.valueOf((int) R.drawable.g29), Integer.valueOf((int) R.drawable.g30)};
    static Integer[] integers14 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.fa_1), Integer.valueOf((int) R.drawable.fa_2), Integer.valueOf((int) R.drawable.fa_3), Integer.valueOf((int) R.drawable.fa_4), Integer.valueOf((int) R.drawable.fa_5), Integer.valueOf((int) R.drawable.fa_6), Integer.valueOf((int) R.drawable.fa_7), Integer.valueOf((int) R.drawable.fa_8), Integer.valueOf((int) R.drawable.fa_9), Integer.valueOf((int) R.drawable.fa_10), Integer.valueOf((int) R.drawable.fa_11), Integer.valueOf((int) R.drawable.fa_12), Integer.valueOf((int) R.drawable.fa_13), Integer.valueOf((int) R.drawable.fa_14), Integer.valueOf((int) R.drawable.fa_15)};
    static Integer[] integers15 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.fest_1), Integer.valueOf((int) R.drawable.fest_2), Integer.valueOf((int) R.drawable.fest_3), Integer.valueOf((int) R.drawable.fest_4), Integer.valueOf((int) R.drawable.fest_5), Integer.valueOf((int) R.drawable.fest_6), Integer.valueOf((int) R.drawable.fest_7), Integer.valueOf((int) R.drawable.fest_8), Integer.valueOf((int) R.drawable.fest_9), Integer.valueOf((int) R.drawable.fest_10), Integer.valueOf((int) R.drawable.fest_11), Integer.valueOf((int) R.drawable.fest_12), Integer.valueOf((int) R.drawable.fest_13), Integer.valueOf((int) R.drawable.fest_14), Integer.valueOf((int) R.drawable.fest_15)};
    static Integer[] integers16 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.frame_1), Integer.valueOf((int) R.drawable.frame_2), Integer.valueOf((int) R.drawable.frame_3), Integer.valueOf((int) R.drawable.frame_4), Integer.valueOf((int) R.drawable.frame_5), Integer.valueOf((int) R.drawable.frame_6), Integer.valueOf((int) R.drawable.frame_7), Integer.valueOf((int) R.drawable.frame_8), Integer.valueOf((int) R.drawable.frame_9), Integer.valueOf((int) R.drawable.frame_10), Integer.valueOf((int) R.drawable.frame_11), Integer.valueOf((int) R.drawable.frame_12), Integer.valueOf((int) R.drawable.frame_13), Integer.valueOf((int) R.drawable.frame_14), Integer.valueOf((int) R.drawable.frame_15)};

    static Integer[] integers = {Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.car), Integer.valueOf((int) R.raw.bicycle), Integer.valueOf((int) R.raw.train), Integer.valueOf((int) R.raw.airplane), Integer.valueOf((int) R.raw.schoolbus), Integer.valueOf((int) R.raw.rocket), Integer.valueOf((int) R.raw.scooter),  Integer.valueOf((int) R.raw.submarine), Integer.valueOf((int) R.raw.van), Integer.valueOf((int) R.raw.fire_truck), Integer.valueOf((int) R.raw.truck), Integer.valueOf((int) R.raw.schoolbus), Integer.valueOf((int) R.raw.boat),  Integer.valueOf((int) R.raw.jetski), Integer.valueOf((int) R.raw.scooter), Integer.valueOf((int) R.raw.tractor), Integer.valueOf((int) R.raw.car), Integer.valueOf((int) R.raw.car), Integer.valueOf((int) R.raw.boat), Integer.valueOf((int) R.raw.airplane), Integer.valueOf((int) R.raw.train), Integer.valueOf((int) R.raw.policecar), Integer.valueOf((int) R.raw.excavator)};
    static Integer[] integers1 = {Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.grapes), Integer.valueOf((int) R.raw.apple), Integer.valueOf((int) R.raw.banana), Integer.valueOf((int) R.raw.cherry), Integer.valueOf((int) R.raw.watermelon), Integer.valueOf((int) R.raw.lemon), Integer.valueOf((int) R.raw.cherry),  Integer.valueOf((int) R.raw.banana), Integer.valueOf((int) R.raw.orange), Integer.valueOf((int) R.raw.strawberry), Integer.valueOf((int) R.raw.grapes), Integer.valueOf((int) R.raw.pear), Integer.valueOf((int) R.raw.peach), Integer.valueOf((int) R.raw.apple), Integer.valueOf((int) R.raw.pear),  Integer.valueOf((int) R.raw.peach), Integer.valueOf((int) R.raw.mango), Integer.valueOf((int) R.raw.apple), Integer.valueOf((int) R.raw.watermelon), Integer.valueOf((int) R.raw.strawberry), Integer.valueOf((int) R.raw.pineapple), Integer.valueOf((int) R.raw.papaya), Integer.valueOf((int) R.raw.coconut), Integer.valueOf((int) R.raw.orange), Integer.valueOf((int) R.raw.kiwi)};
    static Integer[] integers2 = {Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.a_for_apple), Integer.valueOf((int) R.raw.b_for_ball), Integer.valueOf((int) R.raw.c_for_car), Integer.valueOf((int) R.raw.d_for_dog), Integer.valueOf((int) R.raw.e_for_elephant), Integer.valueOf((int) R.raw.f_for_fox), Integer.valueOf((int) R.raw.g_for_goat),  Integer.valueOf((int) R.raw.h_for_hat), Integer.valueOf((int) R.raw.i_for_igloo), Integer.valueOf((int) R.raw.j_for_joker), Integer.valueOf((int) R.raw.k_for_kangaroo), Integer.valueOf((int) R.raw.l_for_lion), Integer.valueOf((int) R.raw.m_for_mouse), Integer.valueOf((int) R.raw.n_for_nest), Integer.valueOf((int) R.raw.o_for_owl), Integer.valueOf((int) R.raw.p_for_pig), Integer.valueOf((int) R.raw.q_for_queen),  Integer.valueOf((int) R.raw.r_for_rabbit), Integer.valueOf((int) R.raw.s_for_sun), Integer.valueOf((int) R.raw.t_for_train), Integer.valueOf((int) R.raw.u_for_umbrella), Integer.valueOf((int) R.raw.v_for_violin), Integer.valueOf((int) R.raw.w_for_whale), Integer.valueOf((int) R.raw.x_for_xlyophone), Integer.valueOf((int) R.raw.y_for_yak), Integer.valueOf((int) R.raw.z_for_zebra)};
    static Integer[] integers3 = {Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.n_1), Integer.valueOf((int) R.raw.n_2), Integer.valueOf((int) R.raw.n_3), Integer.valueOf((int) R.raw.n_4), Integer.valueOf((int) R.raw.n_5), Integer.valueOf((int) R.raw.n_6), Integer.valueOf((int) R.raw.n_7),  Integer.valueOf((int) R.raw.n_8), Integer.valueOf((int) R.raw.n_9), Integer.valueOf((int) R.raw.n_10), Integer.valueOf((int) R.raw.n_11), Integer.valueOf((int) R.raw.n_12), Integer.valueOf((int) R.raw.n_13), Integer.valueOf((int) R.raw.n_14), Integer.valueOf((int) R.raw.n_15), Integer.valueOf((int) R.raw.n_16), Integer.valueOf((int) R.raw.n_17), Integer.valueOf((int) R.raw.n_18), Integer.valueOf((int) R.raw.n_19), Integer.valueOf((int) R.raw.n_20)};
    static Integer[] integers4 = {Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.colortouch2), Integer.valueOf((int) R.raw.colortouch3), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch5), Integer.valueOf((int) R.raw.colortouch6), Integer.valueOf((int) R.raw.colortouch7), Integer.valueOf((int) R.raw.colortouch8), Integer.valueOf((int) R.raw.colortouch9), Integer.valueOf((int) R.raw.colortouch10), Integer.valueOf((int) R.raw.colortouch11), Integer.valueOf((int) R.raw.colortouch12), Integer.valueOf((int) R.raw.colortouch13), Integer.valueOf((int) R.raw.colortouch14), Integer.valueOf((int) R.raw.colortouch15), Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.colortouch2), Integer.valueOf((int) R.raw.colortouch3), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch5), Integer.valueOf((int) R.raw.colortouch6), Integer.valueOf((int) R.raw.colortouch7), Integer.valueOf((int) R.raw.colortouch8), Integer.valueOf((int) R.raw.colortouch9), Integer.valueOf((int) R.raw.colortouch10), Integer.valueOf((int) R.raw.colortouch11), Integer.valueOf((int) R.raw.colortouch12), Integer.valueOf((int) R.raw.colortouch13), Integer.valueOf((int) R.raw.colortouch14)};
    static Integer[] integers17 = {Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.monkey), Integer.valueOf((int) R.raw.fish), Integer.valueOf((int) R.raw.elephant), Integer.valueOf((int) R.raw.turtle), Integer.valueOf((int) R.raw.cow), Integer.valueOf((int) R.raw.horse), Integer.valueOf((int) R.raw.dinosaur),  Integer.valueOf((int) R.raw.hippo), Integer.valueOf((int) R.raw.cat), Integer.valueOf((int) R.raw.giraffe), Integer.valueOf((int) R.raw.pig), Integer.valueOf((int) R.raw.dog), Integer.valueOf((int) R.raw.duck), Integer.valueOf((int) R.raw.toucan), Integer.valueOf((int) R.raw.bear), Integer.valueOf((int) R.raw.kangaroo), Integer.valueOf((int) R.raw.zebra),  Integer.valueOf((int) R.raw.lion), Integer.valueOf((int) R.raw.alligator), Integer.valueOf((int) R.raw.tiger), Integer.valueOf((int) R.raw.squirrel), Integer.valueOf((int) R.raw.zebra), Integer.valueOf((int) R.raw.alligator), Integer.valueOf((int) R.raw.sheep), Integer.valueOf((int) R.raw.horse), Integer.valueOf((int) R.raw.dinosaur), Integer.valueOf((int) R.raw.giraffe), Integer.valueOf((int) R.raw.pig), Integer.valueOf((int) R.raw.rhino), Integer.valueOf((int) R.raw.koala), Integer.valueOf((int) R.raw.cow), Integer.valueOf((int) R.raw.turtle), Integer.valueOf((int) R.raw.squirrel), Integer.valueOf((int) R.raw.monkey), Integer.valueOf((int) R.raw.cat), Integer.valueOf((int) R.raw.elephant), Integer.valueOf((int) R.raw.fish), Integer.valueOf((int) R.raw.dog)};
    static Integer[] integers18 = {Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.teddy_bear), Integer.valueOf((int) R.raw.balloon), Integer.valueOf((int) R.raw.train), Integer.valueOf((int) R.raw.horse), Integer.valueOf((int) R.raw.duck), Integer.valueOf((int) R.raw.stacker), Integer.valueOf((int) R.raw.robot),  Integer.valueOf((int) R.raw.car), Integer.valueOf((int) R.raw.drum), Integer.valueOf((int) R.raw.doll), Integer.valueOf((int) R.raw.blocks), Integer.valueOf((int) R.raw.ball), Integer.valueOf((int) R.raw.airplane),  Integer.valueOf((int) R.raw.rocket), Integer.valueOf((int) R.raw.duck), Integer.valueOf((int) R.raw.horse), Integer.valueOf((int) R.raw.sail_boat), Integer.valueOf((int) R.raw.train), Integer.valueOf((int) R.raw.fire_truck), Integer.valueOf((int) R.raw.doll), Integer.valueOf((int) R.raw.doll), Integer.valueOf((int) R.raw.xylophone), Integer.valueOf((int) R.raw.airplane), Integer.valueOf((int) R.raw.piano), Integer.valueOf((int) R.raw.ball), Integer.valueOf((int) R.raw.teddy_bear)};
    static Integer[] integers19 = {Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.ice_cream), Integer.valueOf((int) R.raw.broccoli), Integer.valueOf((int) R.raw.muffin), Integer.valueOf((int) R.raw.tomato), Integer.valueOf((int) R.raw.pizza), Integer.valueOf((int) R.raw.mushroom), Integer.valueOf((int) R.raw.pumpkin),  Integer.valueOf((int) R.raw.peas), Integer.valueOf((int) R.raw.fries), Integer.valueOf((int) R.raw.cucumber), Integer.valueOf((int) R.raw.cake), Integer.valueOf((int) R.raw.colortouch8), Integer.valueOf((int) R.raw.milk), Integer.valueOf((int) R.raw.tomato), Integer.valueOf((int) R.raw.cheese), Integer.valueOf((int) R.raw.jam), Integer.valueOf((int) R.raw.mushroom),  Integer.valueOf((int) R.raw.chicken), Integer.valueOf((int) R.raw.ice_cream), Integer.valueOf((int) R.raw.eggplant), Integer.valueOf((int) R.raw.hotdog), Integer.valueOf((int) R.raw.cake), Integer.valueOf((int) R.raw.potato), Integer.valueOf((int) R.raw.burger), Integer.valueOf((int) R.raw.cabbage), Integer.valueOf((int) R.raw.colortouch10), Integer.valueOf((int) R.raw.redchilli), Integer.valueOf((int) R.raw.potato), Integer.valueOf((int) R.raw.radish), Integer.valueOf((int) R.raw.cucumber), Integer.valueOf((int) R.raw.onion), Integer.valueOf((int) R.raw.peach), Integer.valueOf((int) R.raw.radish), Integer.valueOf((int) R.raw.eggplant), Integer.valueOf((int) R.raw.corn), Integer.valueOf((int) R.raw.carrot), Integer.valueOf((int) R.raw.capsicum), Integer.valueOf((int) R.raw.burger), Integer.valueOf((int) R.raw.cucumber), Integer.valueOf((int) R.raw.radish)};
    static Integer[] integers20 = {Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.shape_circle), Integer.valueOf((int) R.raw.shape_diamond), Integer.valueOf((int) R.raw.shape_hexagon), Integer.valueOf((int) R.raw.shape_pentagon), Integer.valueOf((int) R.raw.shape_oval), Integer.valueOf((int) R.raw.shape_heart), Integer.valueOf((int) R.raw.shape_rectangle),  Integer.valueOf((int) R.raw.shape_square), Integer.valueOf((int) R.raw.shape_star), Integer.valueOf((int) R.raw.shape_triangle), Integer.valueOf((int) R.raw.shape_rectangle), Integer.valueOf((int) R.raw.shape_oval), Integer.valueOf((int) R.raw.shape_oval), Integer.valueOf((int) R.raw.shape_circle), Integer.valueOf((int) R.raw.shape_hexagon), Integer.valueOf((int) R.raw.shape_triangle), Integer.valueOf((int) R.raw.shape_diamond), Integer.valueOf((int) R.raw.shape_circle), Integer.valueOf((int) R.raw.shape_diamond), Integer.valueOf((int) R.raw.shape_rectangle), Integer.valueOf((int) R.raw.shape_star), Integer.valueOf((int) R.raw.colortouch6), Integer.valueOf((int) R.raw.shape_rectangle), Integer.valueOf((int) R.raw.shape_heart), Integer.valueOf((int) R.raw.colortouch3)};
    static Integer[] integers21 = {Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.colortouch2), Integer.valueOf((int) R.raw.colortouch3), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch5), Integer.valueOf((int) R.raw.colortouch6), Integer.valueOf((int) R.raw.colortouch7), Integer.valueOf((int) R.raw.colortouch8), Integer.valueOf((int) R.raw.colortouch9), Integer.valueOf((int) R.raw.colortouch10), Integer.valueOf((int) R.raw.colortouch11), Integer.valueOf((int) R.raw.colortouch12), Integer.valueOf((int) R.raw.colortouch13), Integer.valueOf((int) R.raw.colortouch14), Integer.valueOf((int) R.raw.colortouch15), Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.colortouch2), Integer.valueOf((int) R.raw.colortouch3), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch5), Integer.valueOf((int) R.raw.colortouch6), Integer.valueOf((int) R.raw.colortouch7), Integer.valueOf((int) R.raw.colortouch8), Integer.valueOf((int) R.raw.colortouch9), Integer.valueOf((int) R.raw.colortouch10), Integer.valueOf((int) R.raw.colortouch11), Integer.valueOf((int) R.raw.colortouch12), Integer.valueOf((int) R.raw.colortouch13), Integer.valueOf((int) R.raw.colortouch14)};
    static Integer[] integers22 = {Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.colortouch2), Integer.valueOf((int) R.raw.colortouch3), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch5), Integer.valueOf((int) R.raw.colortouch6), Integer.valueOf((int) R.raw.colortouch7), Integer.valueOf((int) R.raw.colortouch8), Integer.valueOf((int) R.raw.colortouch9), Integer.valueOf((int) R.raw.colortouch10), Integer.valueOf((int) R.raw.colortouch11), Integer.valueOf((int) R.raw.colortouch12), Integer.valueOf((int) R.raw.colortouch13), Integer.valueOf((int) R.raw.colortouch14), Integer.valueOf((int) R.raw.colortouch15), Integer.valueOf((int) R.raw.colortouch1), Integer.valueOf((int) R.raw.colortouch2), Integer.valueOf((int) R.raw.colortouch3), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch4), Integer.valueOf((int) R.raw.colortouch5), Integer.valueOf((int) R.raw.colortouch6), Integer.valueOf((int) R.raw.colortouch7), Integer.valueOf((int) R.raw.colortouch8), Integer.valueOf((int) R.raw.colortouch9), Integer.valueOf((int) R.raw.colortouch10), Integer.valueOf((int) R.raw.colortouch11)};


    public static Integer[] empty_bitmapIds = {Integer.valueOf((int) R.drawable.bitmap12)};
    static Integer[] integers24 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.puzz_1), Integer.valueOf((int) R.drawable.puzz_2), Integer.valueOf((int) R.drawable.puzz_3), Integer.valueOf((int) R.drawable.puzz_4), Integer.valueOf((int) R.drawable.puzz_5), Integer.valueOf((int) R.drawable.puzz_6), Integer.valueOf((int) R.drawable.puzz_7), Integer.valueOf((int) R.drawable.puzz_8), Integer.valueOf((int) R.drawable.puzz_9), Integer.valueOf((int) R.drawable.puzz_10), Integer.valueOf((int) R.drawable.puzz_11), Integer.valueOf((int) R.drawable.puzz_12), Integer.valueOf((int) R.drawable.puzz_13), Integer.valueOf((int) R.drawable.puzz_14), Integer.valueOf((int) R.drawable.puzz_15), Integer.valueOf((int) R.drawable.puzz_16), Integer.valueOf((int) R.drawable.puzz_17), Integer.valueOf((int) R.drawable.puzz_18), Integer.valueOf((int) R.drawable.puzz_19)};
    static Integer[] integers23 = {Integer.valueOf((int) R.drawable.bitmap12), Integer.valueOf((int) R.drawable.dot_1), Integer.valueOf((int) R.drawable.dot_2), Integer.valueOf((int) R.drawable.dot_3), Integer.valueOf((int) R.drawable.dot_4), Integer.valueOf((int) R.drawable.dot_5), Integer.valueOf((int) R.drawable.dot_6), Integer.valueOf((int) R.drawable.dot_7), Integer.valueOf((int) R.drawable.dot_8), Integer.valueOf((int) R.drawable.dot_9), Integer.valueOf((int) R.drawable.dot_10), Integer.valueOf((int) R.drawable.dot_11), Integer.valueOf((int) R.drawable.dot_12), Integer.valueOf((int) R.drawable.dot_13), Integer.valueOf((int) R.drawable.dot_14), Integer.valueOf((int) R.drawable.dot_15),Integer.valueOf((int) R.drawable.dot_16), Integer.valueOf((int) R.drawable.dot_17), Integer.valueOf((int) R.drawable.dot_18), Integer.valueOf((int) R.drawable.dot_19), Integer.valueOf((int) R.drawable.dot_20), Integer.valueOf((int) R.drawable.dot_21), Integer.valueOf((int) R.drawable.dot_22), Integer.valueOf((int) R.drawable.dot_23), Integer.valueOf((int) R.drawable.dot_24), Integer.valueOf((int) R.drawable.dot_25), Integer.valueOf((int) R.drawable.dot_26), Integer.valueOf((int) R.drawable.dot_27)};
    public static Integer[] bitmapGraphIds = { Integer.valueOf((int) R.drawable.hafe_1), Integer.valueOf((int) R.drawable.hafe_2), Integer.valueOf((int) R.drawable.hafe_3), Integer.valueOf((int) R.drawable.hafe_4), Integer.valueOf((int) R.drawable.hafe_5), Integer.valueOf((int) R.drawable.hafe_6), Integer.valueOf((int) R.drawable.hafe_7), Integer.valueOf((int) R.drawable.hafe_8), Integer.valueOf((int) R.drawable.hafe_9), Integer.valueOf((int) R.drawable.hafe_10), Integer.valueOf((int) R.drawable.hafe_11), Integer.valueOf((int) R.drawable.hafe_12), Integer.valueOf((int) R.drawable.hafe_13), Integer.valueOf((int) R.drawable.hafe_14), Integer.valueOf((int) R.drawable.hafe_15),Integer.valueOf((int) R.drawable.hafe_16), Integer.valueOf((int) R.drawable.hafe_17), Integer.valueOf((int) R.drawable.hafe_18), Integer.valueOf((int) R.drawable.hafe_19), Integer.valueOf((int) R.drawable.hafe_20), Integer.valueOf((int) R.drawable.hafe_21), Integer.valueOf((int) R.drawable.hafe_22), Integer.valueOf((int) R.drawable.hafe_23), Integer.valueOf((int) R.drawable.hafe_24), Integer.valueOf((int) R.drawable.hafe_25), Integer.valueOf((int) R.drawable.hafe_26), Integer.valueOf((int) R.drawable.hafe_27)};

}
